/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospital.management;

import Project.connection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author spaul
 */
public class displaydetails extends javax.swing.JFrame {

    /**
     * Creates new form displaydetails
     */
    public displaydetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "DOB", "Gender", "Blood Group", "Problems", "Address", "Contact no"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTabbedPane1.addTab("Patientdetails", jScrollPane1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Username", "Password", "Email-ID"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTabbedPane1.addTab("Sign In", jScrollPane2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Patient_Name", "Problem", "Date", "Time"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jTabbedPane1.addTab("Cardiologist appointments", jScrollPane3);

        jTable4.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Patient_Name", "Problem", "Date ", "Time"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jTabbedPane1.addTab("Surgeon appointments", jScrollPane4);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Patient_Name", "Problem", "Date", "Time"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        jTabbedPane1.addTab("Neurologist appointments", jScrollPane5);

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Age", "Gender", "Father", "BloodGroup", "Address", "Weight", "TT", "Drug", "Food", "Operation", "Fever", "Disease", "Contact no"
            }
        ));
        jScrollPane6.setViewportView(jTable6);

        jTabbedPane1.addTab("Blood Donation", jScrollPane6);

        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Email", "FeedBack"
            }
        ));
        jScrollPane7.setViewportView(jTable7);

        jTabbedPane1.addTab("Feedback", jScrollPane7);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 1260, 620));

        jComboBox1.setBackground(new java.awt.Color(51, 255, 0));
        jComboBox1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "patientsdetails", "signin", "cardiologist appointments", "Surgeon appointments", "Neurologist appointments", "Blood donation", "Feedback" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 26, 300, 37));

        jButton1.setBackground(new java.awt.Color(255, 0, 51));
        jButton1.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1338, 16, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\spaul\\OneDrive\\Pictures\\w6.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
 String stud = (String) jComboBox1.getSelectedItem();
       
        String name,dob,gender,cno,blo,add,dis,di,b1,b2,patn,pro,date,time,patn2,pro2,date2,time2,patn3,pro3,date3,time3,name1,age,g,fa,bd,ad,we,tt,dg,fo,op,fe,ds,co,na,em,feed;
        
        
          try
          
        {
            Connection con = connection.getCon();
            Statement stmt = con.createStatement();
            
            if(stud=="patientsdetails")
            {
                DefaultTableModel t=(DefaultTableModel) jTable1.getModel();
        t.getDataVector().removeAllElements();
            jTabbedPane1.setVisible(true);
            jTabbedPane1.setSelectedIndex(0);
            ResultSet q;
            q = stmt.executeQuery("select * from patients");
             while (q.next()) {
                name = q.getString("name");
                 dob = q.getString("DOB");
                cno = q.getString("contact");
                blo = q.getString("bloodgroup");
                gender=q.getString("GENDER");
                add=q.getString("ADDRESS");
                dis=q.getString("Problem");
                
                String []rowdata={name,dob,gender,blo,dis,add,cno};
                t.addRow(rowdata);
            }}
            if(stud=="signin"){
                DefaultTableModel t=(DefaultTableModel) jTable2.getModel();
        t.getDataVector().removeAllElements();
                jTabbedPane1.setVisible(true);
            jTabbedPane1.setSelectedIndex(1);
            ResultSet q1;
            q1 = stmt.executeQuery("select * from login");
             while (q1.next()) {
                b1 = q1.getString("username");
           
                di = q1.getString("Email");
               b2 = q1.getString("Password");
                String []rowdata={b1,b2,di};
                t.addRow(rowdata);
             }}
            if(stud=="cardiologist appointments"){
                DefaultTableModel t=(DefaultTableModel) jTable3.getModel();
        t.getDataVector().removeAllElements();
                jTabbedPane1.setVisible(true);
            jTabbedPane1.setSelectedIndex(2);
            ResultSet q2;
            q2 = stmt.executeQuery("select * from appointments1");
             while (q2.next()) {
                patn = q2.getString("patient_name");
           
                pro = q2.getString("problem");
               date = q2.getString("appointment_date");
               time = q2.getString("appointment_time");
                String []rowdata={patn,pro,date,time};
                t.addRow(rowdata);
             }}
            if(stud=="Surgeon appointments"){
                DefaultTableModel t=(DefaultTableModel) jTable4.getModel();
        t.getDataVector().removeAllElements();
                jTabbedPane1.setVisible(true);
            jTabbedPane1.setSelectedIndex(3);
            ResultSet q3;
            q3 = stmt.executeQuery("select * from appointments2");
             while (q3.next()) {
                patn2 = q3.getString("patient_name");
           
                pro2 = q3.getString("problem");
               date2 = q3.getString("appointment_date");
               time2 = q3.getString("appointment_time");
                String []rowdata={patn2,pro2,date2,time2};
                t.addRow(rowdata);
             }}
            if(stud=="Neurologist appointments"){
                DefaultTableModel t=(DefaultTableModel) jTable5.getModel();
        t.getDataVector().removeAllElements();
                jTabbedPane1.setVisible(true);
            jTabbedPane1.setSelectedIndex(4);
            ResultSet q4;
            q4 = stmt.executeQuery("select * from appointments3");
             while (q4.next()) {
                patn3 = q4.getString("patient_name");
           
                pro3 = q4.getString("problem");
               date3 = q4.getString("appointment_date");
               time3 = q4.getString("appointment_time");
                String []rowdata={patn3,pro3,date3,time3};
                t.addRow(rowdata);
             }}
            if(stud=="Blood donation"){
                DefaultTableModel t=(DefaultTableModel) jTable6.getModel();
        t.getDataVector().removeAllElements();
                jTabbedPane1.setVisible(true);
            jTabbedPane1.setSelectedIndex(5);
            ResultSet q5;
            q5 = stmt.executeQuery("select * from Blood");
             while (q5.next()) {
                name1 = q5.getString("name");
                age=q5.getString("age");
                g = q5.getString("gender");
                fa = q5.getString("father");
               bd = q5.getString("blood_group");
               ad = q5.getString("address");
               we = q5.getString("weight");
               tt = q5.getString("TT");
               dg = q5.getString("drug");
               fo = q5.getString("Food");
               op = q5.getString("operation");
               fe = q5.getString("fever");
               ds = q5.getString("disease");
               co = q5.getString("contact");
                String []rowdata={name1,age,g,fa,bd,ad,we,tt,dg,fo,op,fe,ds,co};
                t.addRow(rowdata);
             }}
            if(stud=="Feedback"){
                DefaultTableModel t=(DefaultTableModel) jTable7.getModel();
        t.getDataVector().removeAllElements();
                jTabbedPane1.setVisible(true);
            jTabbedPane1.setSelectedIndex(6);
            ResultSet q6;
            q6 = stmt.executeQuery("select * from feedback");
             while (q6.next()) {
                na = q6.getString("name");
           
                em = q6.getString("email");
               feed = q6.getString("feed");
               
                String []rowdata={na,em,feed};
                t.addRow(rowdata);
             }}
        }
            catch(Exception f)
            { 
            System.out.println(f);
                         }// TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
setVisible(false);
new Addminlogin().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(displaydetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(displaydetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(displaydetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(displaydetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new displaydetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTable jTable7;
    // End of variables declaration//GEN-END:variables
}
