/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospital.management;

/**
 *
 * @author spaul
 */
public class Pharm extends javax.swing.JFrame {

    /**
     * Creates new form Pharm
     */
    public Pharm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        jComboBox8 = new javax.swing.JComboBox<>();
        jComboBox9 = new javax.swing.JComboBox<>();
        jComboBox10 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jComboBox11 = new javax.swing.JComboBox<>();
        jComboBox12 = new javax.swing.JComboBox<>();
        jComboBox13 = new javax.swing.JComboBox<>();
        jComboBox14 = new javax.swing.JComboBox<>();
        jComboBox15 = new javax.swing.JComboBox<>();
        jComboBox16 = new javax.swing.JComboBox<>();
        jComboBox17 = new javax.swing.JComboBox<>();
        jComboBox18 = new javax.swing.JComboBox<>();
        jComboBox19 = new javax.swing.JComboBox<>();
        jComboBox20 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCheckBox1.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jCheckBox1.setText("ACETAMINOPHEN@200");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, -1, -1));

        jCheckBox2.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jCheckBox2.setText("BUPROFEIN@80");
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, -1, -1));

        jCheckBox3.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jCheckBox3.setText("ASPIRIN@60");
        getContentPane().add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, -1, -1));

        jCheckBox4.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jCheckBox4.setText("CETRIZINE@90");
        getContentPane().add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 141, -1));

        jCheckBox5.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jCheckBox5.setText("LORATADINE@300");
        getContentPane().add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, -1, -1));

        jCheckBox6.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jCheckBox6.setText("RANTIDINE@250");
        getContentPane().add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, -1, -1));

        jCheckBox7.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jCheckBox7.setText("OMEPRAZOLE@200");
        getContentPane().add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, -1, -1));

        jCheckBox8.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jCheckBox8.setText("PANTOPRAZOLE@200");
        getContentPane().add(jCheckBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 510, -1, -1));

        jCheckBox9.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jCheckBox9.setText("METFORMIN@190");
        getContentPane().add(jCheckBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 550, -1, -1));

        jCheckBox10.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jCheckBox10.setText("LEVOTHYROXINE@100");
        getContentPane().add(jCheckBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 590, 198, -1));

        jComboBox1.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, -1, -1));

        jComboBox2.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, -1, -1));

        jComboBox3.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, -1, -1));

        jComboBox4.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        getContentPane().add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 350, -1, -1));

        jComboBox5.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        getContentPane().add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, -1, -1));

        jComboBox6.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        getContentPane().add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 430, -1, -1));

        jComboBox7.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        getContentPane().add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 470, -1, -1));

        jComboBox8.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        getContentPane().add(jComboBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 510, -1, -1));

        jComboBox9.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        getContentPane().add(jComboBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 550, -1, -1));

        jComboBox10.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        getContentPane().add(jComboBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 590, -1, -1));

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel1.setText("Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 174, 65, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 175, 335, -1));

        jButton1.setBackground(new java.awt.Color(102, 255, 102));
        jButton1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 700, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Pharmacy");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 40, -1, -1));

        jCheckBox11.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jCheckBox11.setText("ATORVASTATAIN@120");
        getContentPane().add(jCheckBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 230, -1, -1));

        jCheckBox12.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jCheckBox12.setText("SIMVASTATIN@40");
        jCheckBox12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox12ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 280, -1, -1));

        jCheckBox13.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jCheckBox13.setText("LISINOPRIL@200");
        getContentPane().add(jCheckBox13, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 320, -1, -1));

        jCheckBox14.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jCheckBox14.setText("AMOLOCIPINDE@300");
        getContentPane().add(jCheckBox14, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 370, 189, -1));

        jCheckBox15.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jCheckBox15.setText("LOSARTAN@330");
        getContentPane().add(jCheckBox15, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 410, -1, -1));

        jCheckBox16.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jCheckBox16.setText("METROPROCOL@240");
        getContentPane().add(jCheckBox16, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 450, 189, -1));

        jCheckBox17.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jCheckBox17.setText("ALBUTEROL@250");
        getContentPane().add(jCheckBox17, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 490, 163, -1));

        jCheckBox18.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jCheckBox18.setText("FLUTICASONE@100");
        getContentPane().add(jCheckBox18, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 530, 178, -1));

        jCheckBox19.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jCheckBox19.setText("SERTRALINE@250");
        getContentPane().add(jCheckBox19, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 580, -1, -1));

        jCheckBox20.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jCheckBox20.setText("ESCITALOPRAM@220");
        getContentPane().add(jCheckBox20, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 620, 189, -1));

        jComboBox11.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        getContentPane().add(jComboBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 240, -1, -1));

        jComboBox12.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        getContentPane().add(jComboBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 280, -1, -1));

        jComboBox13.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jComboBox13.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        getContentPane().add(jComboBox13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 320, -1, -1));

        jComboBox14.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jComboBox14.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        getContentPane().add(jComboBox14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 370, -1, -1));

        jComboBox15.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jComboBox15.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        getContentPane().add(jComboBox15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 410, -1, -1));

        jComboBox16.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jComboBox16.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        getContentPane().add(jComboBox16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 450, -1, -1));

        jComboBox17.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jComboBox17.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        getContentPane().add(jComboBox17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 490, -1, -1));

        jComboBox18.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jComboBox18.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        getContentPane().add(jComboBox18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 530, -1, -1));

        jComboBox19.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jComboBox19.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        getContentPane().add(jComboBox19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 580, -1, -1));

        jComboBox20.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jComboBox20.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        getContentPane().add(jComboBox20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 620, -1, -1));

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\spaul\\OneDrive\\Pictures\\pharmacy.jpg")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -200, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 int amount=0;
        if(jCheckBox1.isSelected())
        { if(jComboBox1.getSelectedItem()=="1"){
            amount+=200*1;}
         if(jComboBox1.getSelectedItem()=="2"){
            amount+=200*2;}
          if(jComboBox1.getSelectedItem()=="3"){
            amount+=200*3;}
        }
        if(jCheckBox2.isSelected())
        {
            if(jComboBox2.getSelectedItem()=="1"){
            amount+=80*1;}
         if(jComboBox2.getSelectedItem()=="2"){
            amount+=80*2;}
          if(jComboBox2.getSelectedItem()=="3"){
            amount+=80*3;}
        }
        if(jCheckBox3.isSelected()){
            if(jComboBox3.getSelectedItem()=="1"){
            amount+=60*1;}
         if(jComboBox3.getSelectedItem()=="2"){
            amount+=60*2;}
          if(jComboBox3.getSelectedItem()=="3"){
            amount+=60*3;}
        }
        if(jCheckBox4.isSelected())
        {
            if(jComboBox4.getSelectedItem()=="1"){
            amount+=90*1;}
         if(jComboBox4.getSelectedItem()=="2"){
            amount+=90*2;}
          if(jComboBox4.getSelectedItem()=="3"){
            amount+=90*3;}
        }
        if(jCheckBox5.isSelected())
        {
            if(jComboBox5.getSelectedItem()=="1"){
            amount+=300*1;}
         if(jComboBox5.getSelectedItem()=="2"){
            amount+=300*2;}
          if(jComboBox5.getSelectedItem()=="3"){
            amount+=300*3;}
        }
        if(jCheckBox6.isSelected())
        {
            if(jComboBox6.getSelectedItem()=="1"){
            amount+=250*1;}
         if(jComboBox6.getSelectedItem()=="2"){
            amount+=250*2;}
          if(jComboBox6.getSelectedItem()=="3"){
            amount+=250*3;}
        }
        if(jCheckBox7.isSelected())
        {
            if(jComboBox7.getSelectedItem()=="1"){
            amount+=200*1;}
         if(jComboBox7.getSelectedItem()=="2"){
            amount+=200*2;}
          if(jComboBox7.getSelectedItem()=="3"){
            ;amount+=200*3;}
        }
        if(jCheckBox8.isSelected())
        {
           if(jComboBox8.getSelectedItem()=="1"){
            amount+=200*1;}
         if(jComboBox8.getSelectedItem()=="2"){
            amount+=200*2;}
          if(jComboBox8.getSelectedItem()=="3"){
            amount+=200*3;}
        }

        if(jCheckBox9.isSelected())
        {
           if(jComboBox9.getSelectedItem()=="1"){
            amount+=190*1;}
         if(jComboBox9.getSelectedItem()=="2"){
            amount+=190*2;}
          if(jComboBox9.getSelectedItem()=="3"){
            amount+=190*3;}
        }
        if(jCheckBox10.isSelected())
        {
            if(jComboBox10.getSelectedItem()=="1"){
            amount+=100*1;}
         if(jComboBox10.getSelectedItem()=="2"){
            amount+=100*2;}
          if(jComboBox10.getSelectedItem()=="3"){
            amount+=100*3;}
        }
          if(jCheckBox11.isSelected()){
            if(jComboBox11.getSelectedItem()=="1"){
            amount+=120*1;}
         if(jComboBox11.getSelectedItem()=="2"){
            amount+=120*2;}
          if(jComboBox11.getSelectedItem()=="3"){
            amount+=120*3;}
        }
        if(jCheckBox12.isSelected())
        {
            if(jComboBox12.getSelectedItem()=="1"){
            amount+=40*1;}
         if(jComboBox12.getSelectedItem()=="2"){
            amount+=40*2;}
          if(jComboBox12.getSelectedItem()=="3"){
            amount+=40*3;}
        }
        if(jCheckBox13.isSelected())
        {
            if(jComboBox13.getSelectedItem()=="1"){
            amount+=200*1;}
         if(jComboBox13.getSelectedItem()=="2"){
            amount+=200*2;}
          if(jComboBox13.getSelectedItem()=="3"){
            amount+=200*3;}
        }
        if(jCheckBox14.isSelected())
        {
            if(jComboBox14.getSelectedItem()=="1"){
            amount+=300*1;}
         if(jComboBox14.getSelectedItem()=="2"){
            amount+=300*2;}
          if(jComboBox14.getSelectedItem()=="3"){
            amount+=300*3;}
        }
           
        if(jCheckBox15.isSelected())
        {
            if(jComboBox15.getSelectedItem()=="1"){
            amount+=330*1;}
         if(jComboBox15.getSelectedItem()=="2"){
            amount+=330*2;}
          if(jComboBox15.getSelectedItem()=="3"){
            amount+=330*3;}
        }
        if(jCheckBox16.isSelected())
        {
           if(jComboBox16.getSelectedItem()=="1"){
            amount+=240*1;}
         if(jComboBox16.getSelectedItem()=="2"){
            amount+=240*2;}
          if(jComboBox16.getSelectedItem()=="3"){
            amount+=240*3;}
        }
        if(jCheckBox17.isSelected())
        {
            if(jComboBox17.getSelectedItem()=="1"){
            amount+=250*1;}
         if(jComboBox17.getSelectedItem()=="2"){
            amount+=250*2;}
          if(jComboBox17.getSelectedItem()=="3"){
            amount+=250*3;}
        }
        if(jCheckBox18.isSelected())
        {
           if(jComboBox18.getSelectedItem()=="1"){
            amount+=100*1;}
         if(jComboBox18.getSelectedItem()=="2"){
            amount+=100*2;}
          if(jComboBox18.getSelectedItem()=="3"){
            amount+=100*3;}
        }
        if(jCheckBox19.isSelected()){
            if(jComboBox19.getSelectedItem()=="1"){
            amount+=250*1;}
         if(jComboBox19.getSelectedItem()=="2"){
            amount+=250*2;}
          if(jComboBox19.getSelectedItem()=="3"){
            amount+=250*3;}
        }
        if(jCheckBox20.isSelected())
        {
           if(jComboBox20.getSelectedItem()=="1"){
            amount+=220*1;}
         if(jComboBox20.getSelectedItem()=="2"){
            amount+=220*2;}
          if(jComboBox20.getSelectedItem()=="3"){
            amount+=220*3;}
        }
        
        javax.swing.JOptionPane.showMessageDialog(null,"IF YOU NEED ANY OTHER MEDICINE \n DON'T WORRY YOU CAN BUY NEAR BY PHARMACY\nTOTAL:"+amount);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
setVisible(false);
new Hospital1().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCheckBox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox12ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pharm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pharm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pharm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pharm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pharm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox11;
    private javax.swing.JComboBox<String> jComboBox12;
    private javax.swing.JComboBox<String> jComboBox13;
    private javax.swing.JComboBox<String> jComboBox14;
    private javax.swing.JComboBox<String> jComboBox15;
    private javax.swing.JComboBox<String> jComboBox16;
    private javax.swing.JComboBox<String> jComboBox17;
    private javax.swing.JComboBox<String> jComboBox18;
    private javax.swing.JComboBox<String> jComboBox19;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox20;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
